### ISSUE TITLE
About the Difference Between owlii and owlii_vox11

### ISSUE THREAD

**Issue by kai0416s** [NJUVISION/Unicorn#2]
Hi, 
thank you for your excellent open-source work.

I would like to know the difference between the two files owlii and owlii_vox11 under results/PCAC/csvfiles/ours/. 

I noticed the results are slightly different. Looking forward to your reply. 

Thank you!

**Comment by arsx958** [comment]
Thank you very much for pointing this out, owlii is the 10-bit version of owlii_vox11.
